### ISSUE TITLE
Code has too few hacks

### ISSUE THREAD

**Issue by grahamearley** [cpimhoff/End-of-the-Line#4]
Can we have a hack or two more?

**Comment by cpimhoff** [comment]
OH YEAH!?!?!?

`GameObject ignoredFriend = GameObject.Initialize (templateFemaleCharacter);
Dance.GetTheBigDance().SetStartTime(Time.now + (Time.hour * 2));
ignoredFriend.ScaleBeauty(5f);
Notice(ignoredFriend).forTheFirstTime();`
